baseurl = "http://www.dandersondata.com"
DefaultContentLanguage = "en"
title = "Data Science in Education"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
disqusShortname = "http-www-dandersondata-com"
#googleAnalytics = "XXX"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[Params]
  subtitle = "A blog by Daniel Anderson"
  logo = "img/scatter.png"
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  comments = true

[[Params.bigimg]]
  src = "img/bg.jpg"
  desc = "Toketee falls, Umpqua National Forest"

[Author]
  name = "Daniel Anderson"
  website = "http://www.dandersondata.com"
  email = "daniela@uoregon.edu"
  github = "DJAnderson07"
  twitter = "DJAnderson_07"
  stackoverflow = "users/4959854/daniel-anderson"
 
[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    identifier = "vita_docs"
    name = "Vita"
    weight = 3

[[menu.main]]
    parent = "vita_docs"
    name = "conference presentations"
    url = "page/conference_pres"
    weight = 1

[[menu.main]]
    parent = "vita_docs"
    name = "publications"
    url = "page/publications"
    weight = 1

[[menu.main]]
    parent = "vita_docs"
    name = "software"
    url = "page/software"
    weight = 1

[[menu.main]]
    parent = "vita_docs"
    name = "teaching"
    url = "page/teaching"
    weight = 1

[[menu.main]]
    name = "esvis"
    url = "page/esvis/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
