baseurl = "http://example.org"
title = "Dimension"
theme = "dimension"
languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = true
disableKinds=["RSS"]

[params]
  description = '<!--[-->A fully responsive site template designed by <a href="https://html5up.net">HTML5 UP</a> and released<!--]--><br />
                <!--[-->for free under the <a href="https://html5up.net/license">Creative Commons</a> license.<!--]-->'
  logo = "fa-diamond"
  copyright = "Untitled"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "#"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "#"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "#"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "#"

[languages]
[languages.en]
languageName = "English"
weight = 1

[languages.de]
languageName = "Deutsch"
weight = 2
title = "Dimension"
description = '<!--[-->A fully responsive site template designed by <a href="https://html5up.net">HTML5 UP</a> and released<!--]--><br />
                <!--[-->for free under the <a href="https://html5up.net/license">Creative Commons</a> license.<!--]-->'
